steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--build-arg',
    'AQUABOT_SECRETS_KEY=$$AQUABOT_SECRETS_PEM',
    '-t',
    'gcr.io/$PROJECT_ID/aquabot',
    '.'
  ]
- name: 'gc.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/aquabot',
  ]

secrets:
- kmsKeyName: projects/$PROJECT_ID/locations/${REGION}/keyRings/${KMS_KEY_RING_NAME}/cryptoKeys/${AQUABOT_SECRET_KMS_CRYPTO_KEY}
  secretEnv:
    AQUABOT_SECRETS_PEM: ${AQUABOT_SECRETS_PEM_ENC_BASE64}
