steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'kms',
    'decrypt',
    '--ciphertext-file=aquabot_pem_kms_ciphertext.enc',
    '--plaintext-file=/root/.ssh/id_rsa',
    '--location=us-central1',
    '--keyring=oa-shared-kms-ring',
    '--key=aquabot_secret_pem'
  ]
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    ssh-keyscan github.com >> /root/.ssh/known_hosts
    git clone --recurse-submodules git@github.com:order-of-axis-association/AquaBot.git
    mkdir -p /root/.ssh/secrets
    cp -r AquaBot/secrets /root/.ssh/
    ls -al AquaBot/
    ls -al AquaBot/secrets
    ls -al /root/.ssh
    ls -al /root/.ssh/secrets
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'gcr.io/$PROJECT_ID/aquabot',
    '.'
  ]
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'gc.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/aquabot',
  ]
