steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'gcr.io/$PROJECT_ID/aquabot',
    '.'
  ]
- name: 'gc.io/cloud-builders/docker'
  args: [
    'push',
    'gcr.io/$PROJECT_ID/aquabot',

  ]
