GOCMD=go
GOBUILD=$(GOCMD) build
GOGET=$(GOCMD) get

BINARY_PATH=bin/
BINARY_NAME=aqua
BINARY_FULL_PATH=$(BINARY_PATH)$(BINARY_NAME)

all: build
build:
	$(GOGET) -d ./...
	$(GOBUILD) -o $(BINARY_FULL_PATH) main.go
